### ISSUE TITLE
Что такое "инцидентных юридическим лицам"?

### ISSUE THREAD

**Issue by epogrebnyak** [finnethackaton/finnet#1]
> удалено 100000 рёбер, инцидентных юридическим лицам из файла ids.csv.

соответствующих юридическим лицам? привязанных к юридическим лицам?

**Comment by lipoponi** [comment]
Ребро инциндентно вершине, если вершина является одним из концов ребра

**Comment by epogrebnyak** [comment]
Спасибо!
